name: Build plugin image

on:
  push:
    tags:
      - 'v*.*.*'
      - 'V.*.*.*'
      - 'V*.*.*'
      - 'v.*.*.*'

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: |
              echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
              echo $RELEASE_VERSION
              echo ${{ env.RELEASE_VERSION }}

      - name: setup docker
        uses: docker-practice/actions-setup-docker@master

      - name: build docker image
        run: |
              docker build -t ghcr.io/orange-cloudfoundry/headlamp-plugin:${{ env.RELEASE_VERSION }} ./

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push docker image
        run: |
              docker push ghcr.io/orange-cloudfoundry/headlamp-plugin:${{ env.RELEASE_VERSION }}
